### ISSUE TITLE
Certstream Python - SIGFPE

### ISSUE THREAD

**Issue by Asentrixx** [CaliDog/CertStream-Server#117]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Scripts\certstream.exe\__main__.py", line 4, in <module>
  File "C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\site-packages\certstream\cli.py", line 8, in <module>
    from signal import signal, SIGPIPE, SIG_DFL
ImportError: cannot import name 'SIGPIPE' from 'signal' (C:\Users\X\AppData\Local\Programs\Python\Python312\Lib\signal.py). Did you mean: 'SIGFPE'?

Using Python 3.12.2

**Comment by d-Rickyy-b** [comment]
Seems like you were having this issue with the python client library: https://github.com/CaliDog/certstream-python.

Also you are probably running the python client on Windows 10? Because SIGPIPE doesn't seem to be available on Windows 10. See https://stackoverflow.com/questions/58718659/cannot-import-name-sigpipe-from-signal-in-windows-10

Duplicate of https://github.com/CaliDog/certstream-python/issues/36
