### ISSUE TITLE
certificate_expired, 'TLS client: In state certify at ssl_handshake.erl:1691 generated CLIENT ALER

### ISSUE THREAD

**Issue by senf666** [CaliDog/certstream-server#14]
I did the following
```
git clone https://github.com/CaliDog/certstream-server.git
cd certstream-server/
mix deps.get
mix run --no halt
```

When doing a mix run I see this error every 10 seconds or so:
```
13:37:05.466 [info]  Worker #PID<0.1940.0> with url ct.googleapis.com/skydiver/ found 112 certificates [263324306 -> 263324418].

13:37:05.466 [info]  GETing https://ct.googleapis.com/skydiver/ct/v1/get-entries?start=263324306&end=263324369

13:37:05.471 [info]  Worker #PID<0.1943.0> with url ct.googleapis.com/testtube/ found 22 certificates [105562058 -> 105562080].

13:37:05.471 [info]  GETing https://ct.googleapis.com/testtube/ct/v1/get-entries?start=105562058&end=105562079

13:37:05.490 [info]  GETing https://ct.googleapis.com/pilot/ct/v1/get-entries?start=865899493&end=865899556

13:37:05.574 [info]  TLS client: In state certify at ssl_handshake.erl:1691 generated CLIENT ALERT: Fatal - Certificate Expired


13:37:05.576 [error] GenServer #PID<0.2251.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:tls_alert, {:certificate_expired, 'TLS client: In state certify at ssl_handshake.erl:1691 generated CLIENT ALERT: Fatal - Certificate Expired\n'}} of type Tuple. This protocol is implemented for the following type(s): Decimal, Version.Requirement, BitString, NaiveDateTime, Date, Atom, Integer, List, DateTime, Time, Version, URI, Float
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (certstream) lib/ct_watcher.ex:152: Certstream.CTWatcher.fetch_tree_size/1
    (certstream) lib/ct_watcher.ex:95: Certstream.CTWatcher.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :update

13:37:05.577 [info]  Worker #PID<0.2263.0> started with url plausible.ct.nordu.net/.

13:37:05.881 [info]  GETing https://ct.cloudflare.com/logs/nimbus2020/ct/v1/get-entries?start=159823031&end=159823094

13:37:06.592 [info]  GETing https://ct.cloudflare.com/logs/nimbus2020/ct/v1/get-entries?start=159823095&end=159823158

13:37:06.595 [info]  GETing https://ct.googleapis.com/skydiver/ct/v1/get-entries?start=263324370&end=263324417

13:37:07.109 [info]  GETing https://ct.googleapis.com/pilot/ct/v1/get-entries?start=865899557&end=865899620

13:37:07.323 [info]  GETing https://ct.cloudflare.com/logs/nimbus2020/ct/v1/get-entries?start=159823159&en
```

The WebSocket server is fine and I can subscribe.
What's that saying? One of the certificate transparency logs has a bad certificate ?

Thanks.

**Comment by senf666** [comment]
Anyone got any ideas? @Fitblip @brint @madhuakula  perhaps :)

**Comment by Fitblip** [comment]
Hi @DannyCork - this looks to be a bad CT server we're connecting to (with an expired certificate) and a bug (since we try to coerce `reason` to a string, which isn't defined for that type)!

Not sure which CT server is causing issues, but because of the awesomeness of supervisor trees, you should be able to safely ignore this warning.

**Comment by senf666** [comment]
excellent thanks for the heads up.
